### ISSUE TITLE
RT-AC86U check git and opkg version failed

### ISSUE THREAD

**Issue by liguo86** [Acris/shadowsocks-asuswrt-merlin#1]
```
  if ! command -v git > /dev/null 2>&1; then
    echo -e "$ansi_red Error: git is not installed, please install git first! $ansi_std"
    exit 1
  fi

  if ! command -v opkg > /dev/null 2>&1; then
    echo -e "$ansi_red Error: opkg is not found, please install Entware first! $ansi_std"
    exit 1
  fi
```
my 'RT-AC86U' router is installed git and opkg, but run install.sh is failed at these if.
run 'git --version' or 'opkg -v' is success.

**Comment by Acris** [comment]
Hi,
Do you installed bash? 
`command` is built in bash, you can install all the prerequisites by:
 `opkg install bash ca-certificates git-http wget` . 

Then just run the following command to install shadowsocks-asuswrt-merlin:
`bash -c "$(wget https://raw.githubusercontent.com/Acris/shadowsocks-asuswrt-merlin/master/tools/install.sh -O -)"`

**Comment by Acris** [comment]
I closed the issue because no further activity occurs, feel free to reopen it if needed.
