### ISSUE TITLE
Force pass proxy help needed

### ISSUE THREAD

**Issue by 8lexliu** [Acris/shadowsocks-asuswrt-merlin#12]
I tried to add _software.sonymobile.com_ by following steps but not working as intended

1: vi /opt/share/ss-merlin/rules/user_domain_name_gfwlist.txt
2: add _software.sonymobile.com_ to the list and save it
3: ss-merlin restart

Am I did something wrong or there is a specific format required when adding domain to this list?

Thank you for your excellent work!

**Comment by Acris** [comment]
It's a bug, I'll fix it later.

**Comment by Acris** [comment]
Hi, can you run `ss-merlin upgrade` and test again?

**Comment by 8lexliu** [comment]
tried a clean install, but the issue still exists. maybe there's something wrong with settings?
Add _software.sonymobile.com_ to the user_domain_name_gfwlist.txt and run ss-restart command then download a package from _https://software.sonymobile.com/filestorage/20078660/0365fa46c928206803764e0944aa2f6d_part0_ but traffic still doesn't pass the proxy.

**Comment by Acris** [comment]
Can you execute the following commands separately and paste the output here?
```
iptables -t nat -L
ipset list usergfwlist
cat /opt/share/ss-merlin/etc/dnsmasq.d/user-gfwlist-domains.conf
```

**Comment by 8lexliu** [comment]
`iptables -t nat -L`
[OUTPUT](https://pastebin.com/UkNXfdxZ)
`ipset list usergfwlist`
OUTPUT: [ipset] v7.1: The set with the given name does not exist
`cat /opt/share/ss-merlin/etc/dnsmasq.d/user-gfwlist-domains.conf`
OUTPUT:ipset=/software.sonymobile.com/usergfwlist

**Comment by Acris** [comment]
I fixed this issue, please upgrade ss-merlin by `ss-merlin upgrade` to the latest version and try again.

**Comment by 8lexliu** [comment]
Fixed
Thanks 😊
