### ISSUE TITLE
Failed when unpacking objects.

### ISSUE THREAD

**Issue by KinseyWang** [Acris/shadowsocks-asuswrt-merlin#13]
Hi Acris,
Thanks for your project.
After I entered this command, I got this error:
![image](https://user-images.githubusercontent.com/3963925/61185689-c1e3a800-a68e-11e9-8e9d-ab3aeff8bf45.png)
I tried couple times but it doesn't work, what should I do to solve this?

**Comment by 8lexliu** [comment]
Network issue at your side.

**Comment by Acris** [comment]
Network issue, you can try it again.

**Comment by KinseyWang** [comment]
> Network issue, you can try it again.

Thanks for your reply. I just did this at home and I tried it whole night, no go. Might because the network is non-vpn? Should I try a proxy network?

**Comment by KinseyWang** [comment]
Hi Acris,

I've solved the problem by a retry and finished the deployment but I it doesn't work on my laptop and TV. What the problem it could be? When I dig google, it seems work.
![image](https://user-images.githubusercontent.com/3963925/61228169-4ea66880-a758-11e9-9efd-6b813aa17a52.png)

Here's the configuration:
config.json
![image](https://user-images.githubusercontent.com/3963925/61228268-83b2bb00-a758-11e9-9f33-9500bcd59a3b.png)
ss-merlin.conf
![image](https://user-images.githubusercontent.com/3963925/61228352-b492f000-a758-11e9-8160-a2f9be152d86.png)

HELP!

**Comment by Acris** [comment]
Did you deployed v2ray-plugin on your server side?

**Comment by KinseyWang** [comment]
Hi Acris,

It works now!!! Thank you so much!!! I just removed plugin and plugin_opts in the config file and restarted ss-merlin service.
BTW, what is the v2ray-plugin? Actually I set up v2ray on my server and enabled ss feature... seems like ss is a plugin...

 Two more questions, are all the files stored on my U-Disk? Will I lost everything if I restart my Asus router?

Thanks!

**Comment by Acris** [comment]
1. https://github.com/shadowsocks/v2ray-plugin
2. It's OK to restart the router.

**Comment by KinseyWang** [comment]
Thanks Acris. It works so well except Google Home...
I've set it up on my phone but it kept saying: "Your Google Home isn't set up yet, to get started download the Google Home App". 

I added the following code into /etc/firewall.user followed this guide:https://gist.github.com/willwhui/28e8896b6e4560f1cf0d32a5acf501f3

iptables -I PREROUTING -t nat -p tcp -d 8.8.4.4 --dport 53 -j REDIRECT --to-ports 1053
iptables -I PREROUTING -t nat -p tcp -d 8.8.8.8 --dport 53 -j REDIRECT --to-ports 1053

no go...I'm not sure if it is ss issue or not.

**Comment by Acris** [comment]
Remove your iptables rule and try to set mode=1 and udp=1  in `ss-merlin.conf`, then see if the problem can be solved.

**Comment by KinseyWang** [comment]
Thanks for your suggestion. it doesn't work, I'm still looking for the solution...

**Comment by Acris** [comment]
Issue closed, feel free to re-open it if needed.
