### ISSUE TITLE
启用插件以后怎么切换模式？例如全局，或者大陆白名单

### ISSUE THREAD

**Issue by bobbyvont** [Acris/shadowsocks-asuswrt-merlin#2]
请问启用插件以后怎么切换模式？例如全局，或者大陆白名单
无法访问GOOGLE，youtube正常
ip138还是显示国内的IP

**Comment by Acris** [comment]
目前无法切换，只有大陆白名单一种模式。
如果YouTube正常，Google无法访问的话，尝试清空下本机DNS缓存，如Windows系统的话可以执行`ipconfig /flushdns`。
若还无法访问，建议尝试使用`ss-merlin restart`重启一下服务。

**Comment by bobbyvont** [comment]
> 目前无法切换，只有大陆白名单一种模式。
> 如果YouTube正常，Google无法访问的话，尝试清空下本机DNS缓存，如Windows系统的话可以执行`ipconfig /flushdns`。
> 若还无法访问，建议尝试使用`ss-merlin restart`重启一下服务。

清除了DNS缓存可以了，十分感谢你百忙之中抽空回复我。

**Comment by Acris** [comment]
@bobbyvont 目前已经实现了模式切换功能。
运行`ss-merlin upgrade`执行更新，然后编辑`/opt/share/ss-merlin/etc/ss-merlin.conf`：
- mode=0为GFW list模式（默认）
- mode=1为大陆和局域网白名单模式
- mode=2为全局模式

还可以修改udp字段来决定是否启用UDP relay，如需启用，要确保服务端支持UDP，并且客户端的配置文件中，`mode` 为 `tcp_and_udp`。

详情可以阅读 [README](https://github.com/Acris/shadowsocks-asuswrt-merlin/blob/master/README.md)。
