### ISSUE TITLE
为什么无法安装了

### ISSUE THREAD

**Issue by najloa** [Acris/shadowsocks-asuswrt-merlin#20]
上一个版本可以正常安装使用，但是今天无意间发现有CPU2满载的问题，刚准备重装排障就遇到问题了，麻烦作者看看是不是今天的更新的问题

```
 Checking installation environment...
git version 2.22.0
opkg version dcbc142e51f5f5f2fb9e4e44657e013d3c36a52b (2019-06-14)
 Installing required packages...
Downloading http://bin.entware.net/armv7sf-k2.6/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
Installing haveged (1.9.6-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/haveged_1.9.6-1_armv7-2.6.ipk
Installing libhavege (1.9.6-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libhavege_1.9.6-1_armv7-2.6.ipk
Unknown package 'unbound'.
Installing ipset (7.3-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/ipset_7.3-1_armv7-2.6.ipk
Installing libmnl (1.0.4-2) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libmnl_1.0.4-2_armv7-2.6.ipk
Installing libipset (7.3-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libipset_7.3-1_armv7-2.6.ipk
Installing iptables (1.4.21-3) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/iptables_1.4.21-3_armv7-2.6.ipk
Configuring libmnl.
Configuring libhavege.
Configuring haveged.
Configuring libipset.
Configuring ipset.
Configuring iptables.
Collected errors:
 * opkg_install_cmd: Cannot install package unbound.
admin@R7000:/tmp/home/root#
```

**Comment by Acris** [comment]
尝试执行`opkg update && opkg install unbound`，看下输出信息。

**Comment by najloa** [comment]
> 尝试执行`opkg update && opkg install unbound`，看下输出信息。

admin@R7000:/tmp/home/root# opkg update && opkg install unbound
Downloading http://bin.entware.net/armv7sf-k2.6/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
Unknown package 'unbound'.
Collected errors:
 * opkg_install_cmd: Cannot install package unbound.

错误信息是一样的

**Comment by najloa** [comment]
admin@R7000:/tmp/home/root# sh -c "$(wget https://raw.githubusercontent.com
/Acris/shadowsocks-asuswrt-merlin/master/tools/install.sh -O -)"
--2019-10-08 18:32:39--  https://raw.githubusercontent.com/Acris/shadowsocks-asuswrt-merlin/master/tools/install.sh
Resolving raw.githubusercontent.com... 151.101.108.133
Connecting to raw.githubusercontent.com|151.101.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3389 (3.3K) [text/plain]
Saving to: 'STDOUT'

-                   100%[===================>]   3.31K  --.-KB/s    in 0s

2019-10-08 18:32:40 (13.0 MB/s) - written to stdout [3389/3389]

 Checking installation environment...
git version 2.22.0
opkg version dcbc142e51f5f5f2fb9e4e44657e013d3c36a52b (2019-06-14)
 Installing required packages...
Downloading http://bin.entware.net/armv7sf-k2.6/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
Installing haveged (1.9.6-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/haveged_1.9.6-1_armv7-2.6.ipk
Installing libhavege (1.9.6-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libhavege_1.9.6-1_armv7-2.6.ipk
Unknown package 'unbound'.
Installing ipset (7.3-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/ipset_7.3-1_armv7-2.6.ipk
Installing libmnl (1.0.4-2) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libmnl_1.0.4-2_armv7-2.6.ipk
Installing libipset (7.3-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libipset_7.3-1_armv7-2.6.ipk
Installing iptables (1.4.21-3) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/iptables_1.4.21-3_armv7-2.6.ipk
Configuring libmnl.
Configuring libhavege.
Configuring haveged.
Configuring libipset.
Configuring ipset.
Configuring iptables.
Collected errors:
 * opkg_install_cmd: Cannot install package unbound.

**Comment by najloa** [comment]
看不太懂，是因为opkg源里没有unbound才出错的吗？
admin@R7000:/tmp/home/root# opkg list | grep unbound
asterisk16-res-resolver-unbound - 16.3.0-6 - Unbound DNS resolver support.
libunbound - 1.9.3-1 - This package contains the Unbound shared library with basic includes necessary to meet the needs of UCI/LuCI configuration optoins.
unbound-anchor - 1.9.3-1 - This package contains the Unbound anchor utility.
unbound-control - 1.9.3-1 - This package contains the Unbound control utility.
unbound-control-setup - 1.9.3-1 - This package contains the Unbound control setup utility.
unbound-daemon - 1.9.3-1 - This package contains the Unbound daemon with basic includes necessary to meet the needs of UCI/LuCI configuration optoins.
unbound-host - 1.9.3-1 - This package contains the Unbound DNS lookup utility.
admin@R7000:/tmp/home/root#

admin@R7000:/tmp/home/root#  opkg install  curl bash
Installing curl (7.66.0-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/curl_7.66.0-1_armv7-2.6.ipk
Installing bash (5.0-3) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/bash_5.0-3_armv7-2.6.ipk
Installing libncursesw (6.1-5) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libncursesw_6.1-5_armv7-2.6.ipk
Installing libncurses (6.1-5) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libncurses_6.1-5_armv7-2.6.ipk
Installing libreadline (8.0-1a) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libreadline_8.0-1a_armv7-2.6.ipk
Configuring libncursesw.
Configuring libncurses.
Configuring libreadline.
Configuring bash.
Configuring curl.

**Comment by Acris** [comment]
目前没有路由器可以测试，麻烦帮忙测试下执行`opkg update && opkg install unbound-daemon`，然后执行`unbound --help`看下输出？

**Comment by najloa** [comment]
> 目前没有路由器可以测试，麻烦帮忙测试下执行`opkg update && opkg install unbound-daemon`，然后执行`unbound --help`看下输出？

admin@R7000:/tmp/home/root# opkg update && opkg install unbound-daemon
Downloading http://bin.entware.net/armv7sf-k2.6/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
Installing unbound-daemon (1.9.3-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/unbound-daemon_1.9.3-1_armv7-2.6.ipk
Installing zlib (1.2.11-3) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/zlib_1.2.11-3_armv7-2.6.ipk
Installing libopenssl (1.1.1d-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libopenssl_1.1.1d-1_armv7-2.6.ipk
Installing libunbound (1.9.3-1) to root...
Downloading http://bin.entware.net/armv7sf-k2.6/libunbound_1.9.3-1_armv7-2.6.ipk
Configuring zlib.
Configuring libopenssl.
Configuring libunbound.
Configuring unbound-daemon.
admin@R7000:/tmp/home/root# unbound --help
unbound: invalid option -- '-'
usage:  unbound [options]
        start unbound daemon DNS resolver.
-h      this help.
-c file config file to read instead of /opt/var/lib/unbound/unbound.conf
        file format is described in unbound.conf(5).
-d      do not fork into the background.
-p      do not create a pidfile.
-v      verbose (more times to increase verbosity).
-V      show version number and build options.

Version 1.9.3
BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
admin@R7000:/tmp/home/root#

admin@R7000:/tmp/home/root# unbound
[1570601927] unbound[1665:0] error: Could not open /opt/var/lib/unbound/unbound.conf: No such file or directory
[1570601927] unbound[1665:0] warning: Continuing with default config settings
[1570601927] unbound[1665:0] error: can't bind socket: Cannot assign requested address for ::1 port 53
[1570601927] unbound[1665:0] fatal error: could not open ports
admin@R7000:/tmp/home/root#

**Comment by najloa** [comment]
> 目前没有路由器可以测试，麻烦帮忙测试下执行`opkg update && opkg install unbound-daemon`，然后执行`unbound --help`看下输出？
我把install.sh里面的opkg install unbound替换成opkg install unbound-daemon后，已经可以正常安装使用了

**Comment by Acris** [comment]
感谢测试，应该是entware拆分了unbound包名，稍后我将修正安装脚本。
