### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by BXXXXO** [Acris/shadowsocks-asuswrt-merlin#23]
你好。很感谢你为原版merlin开发了这个功能。没有找到相关的教程，只好在这里请教下几个问题：

1、v2ray插件怎么配置？
2、客户端需要设置socks的1080端口吗？
3、gfwlist是自动维护的吧，那whitelist怎么办？
非常感谢。

**Comment by Acris** [comment]
1、服务端配置参见：https://github.com/Acris/docker-shadowsocks-libev#enable-v2ray-plugin，如果不需要开启tls可以去掉证书相关配置，客户端（即路由器上）配置保持与服务端一致。
2、你安装的就是客户端，端口默认是1080。
3、gfwlist和IP白名单都是自动更新，用户自定义的白名单由用户维护。

**Comment by BXXXXO** [comment]
> 1、服务端配置参见：https://github.com/Acris/docker-shadowsocks-libev#enable-v2ray-plugin ，如果不需要开启tls可以去掉证书相关配置，客户端（即路由器上）配置保持与服务端一致。
> 2、你安装的就是客户端，端口默认是1080。
> 3、gfwlist和IP白名单都是自动更新，用户自定义的白名单由用户维护。

感谢回复，还是有点不太清楚。我理解我在路由器上安装的就是相当于电脑或者手机上的客户端。也就是你说的第2点。但客户端端口1080用处是什么？在电脑上，可以允许其它设备通过1080端口连接代理。但在路由器上的端口，是什么用处？你在另外一个回复中说其它电脑不用配置直接就可以使用。
多谢。

**Comment by Acris** [comment]
1080端口用于路由器上的iptables将流量转发至ss-redir，即透明代理。

**Comment by BXXXXO** [comment]
这下明白了非常感谢。。

2019年12月30日 下午4:34，Acris Liu <notifications@github.com>写道：

1080端口用于路由器上的iptables将流量转发至ss-redir，即透明代理。
