### ISSUE TITLE
透明代理不工作吗？

### ISSUE THREAD

**Issue by BXXXXO** [Acris/shadowsocks-asuswrt-merlin#24]
实在不好意思，还有一个问题：运行正常，国内网站没问题，但不能翻墙。
我Chrome是直接连接和1080端口代理都试了，还是不行。
请帮忙看看。
谢谢。

youtube,twitter是一个情况：
This site can’t be reachedwww.youtube.com refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

Google play　另外一种
This site can’t be reachedThe webpage at https://play.google.com/store might be temporarily down or it may have moved permanently to a new web address.
ERR_QUIC_PROTOCOL_ERROR

配置如下：
【ss-merlin.conf】
```
# Route mode
## 0: GFW list.
## 1: Bypass mainland China.
## 2: Global mode.
mode=0

# UDP support
## 0: Disable UDP.
## 1: Enable UDP, require server side support.
udp=0

# LAN IPs
## Configure which LAN IP will pass transparent proxy.
## Default is 0.0.0.0/0, means all LAN devices will affected.
## You can assign a LAN IP like 192.169.1.125 means only this device can pass transparent proxy.
lan_ips=0.0.0.0/0

# China DNS IP
## Default is 119.29.29.29
china_dns_ip=119.29.29.29
```

【config.json】
```
{
  "server": "****",
  "server_port": 16534,
  "password": "****",
  "method": "chacha20-ietf-poly1305",
  "local_address": "0.0.0.0",
  "local_port": 1080,
  "timeout": 600,
  "mode": "tcp_only"
  }
```

ipset / iptable 见附件。

我用的是公司内网，和这个有关系吗？公司是192.168.55.1网段，我路由器是192.168.0.1

[etc.zip](https://github.com/Acris/shadowsocks-asuswrt-merlin/files/4002303/etc.zip)

**Comment by Acris** [comment]
路由器配置好后，电脑端无需做其他配置。
先确认下客户端shadowsocks配置有没问题，可以通过`ss-merlin stop`先停掉软件，然后单独执行`ss-redir -c /opt/share/ss-merlin/etc/shadowsocks/config.json`，看下日志有无认证失败等信息。

**Comment by Acris** [comment]
问题解决了吗？

**Comment by BXXXXO** [comment]
> 问题解决了吗？

不好意思，最近一直没时间研究。
# ss-redir -c /opt/share/ss-merlin/etc/shadowsocks/config.json
 2020-01-02 10:59:10 INFO: initializing ciphers... chacha20-ietf-poly1305
 2020-01-02 10:59:10 INFO: listening at 0.0.0.0:1080
 2020-01-02 10:59:10 INFO: running from root user

然后就停止在这个界面

**Comment by Acris** [comment]
暂时不支持自动切换服务器。
