### ISSUE TITLE
config.json中v2ray配置

### ISSUE THREAD

**Issue by BXXXXO** [Acris/shadowsocks-asuswrt-merlin#26]
您好。现在标准的SS已经配置好了，想加上v2ray plugin。我仔细研究了您的回复（服务端配置参见：https://github.com/Acris/docker-shadowsocks-libev#enable-v2ray-plugin ，如果不需要开启tls可以去掉证书相关配置，客户端（即路由器上）配置保持与服务端一致。）也去https://github.com/Acris/docker-shadowsocks-libev#enable-v2ray-plugin研究了半天，实在没搞明白。

下面是我的v2ray客户端配置，config.json应该如何写？谢谢。

```
  "outbounds": [
        {
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "X.X.X.X",
                        "port": 443,
                        "users": [
                            {
                                "id": "0ffe665c-.......7269",
                                "level": 1,
                                "alterId": 4
                            }
                        ]
                    }
                ]
            }
        }
    ],
```

情况是：服务器1-n支持ss，另外一个服务器x支持v2ray连接。这种情况下，这样配置config.json只要注明两个服务器就没问题吧？

另外，我不太理解ss的v2ray plugin的场景。如果加上v2ray，流量就全按v2ray走，不再走ss吗？谢谢

**Comment by Acris** [comment]
v2ray和shadowsocks的v2ray plugin是两个不一样的东西，目前不支持v2ray。

**Comment by BXXXXO** [comment]
> v2ray和shadowsocks的v2ray plugin是两个不一样的东西，目前不支持v2ray。

原来这样。他们起相同的名字，实在让人困惑。
您有写一个v2ray的项目计划吗？现在ss太容易被识别。

**Comment by Acris** [comment]
目前暂无支持v2ray计划，自用的ss + v2ray plugin一直状态良好。

**Comment by BXXXXO** [comment]
明白。非常感谢

2020年1月2日 下午2:44，Acris Liu <notifications@github.com>写道：

目前暂无支持v2ray计划，自用的ss + v2ray plugin一直状态良好。
