### ISSUE TITLE
运动一段时间就无法访问外网

### ISSUE THREAD

**Issue by BXXXXO** [Acris/shadowsocks-asuswrt-merlin#27]
您好。
我在AC3100+梅林原版384.14_2固件上面部署后，采取 1: Bypass mainland China方式，刚运行时一切都正常。
访问ip111.cn，显示是这样的：
从国内测试：国内ip
从国外测试: ss服务器ip
从谷歌测试： ss服务器ip

过不了多久就出现所有外网不能访问，内网不受影响的情况。
访问ip111.cn，显示是这样的：
从国内测试：国内ip
从国外测试: ss服务器ip
从谷歌测试：空白

（而且很奇怪，好像ssh也受到影响，再登录的时候输入完密码后直接闪退。）

只能重启路由器，再ssh过去，再启动又正常访问外网。

有没有日志可以检查是哪个环节出问题了吗？

谢谢。

**Comment by Acris** [comment]
登录路由器后台，左侧系统记录，保存日志然后上传看看。

**Comment by BXXXXO** [comment]
您好。日志如下：
启动ss服务，电脑连接了一下谷歌市场，看了一段几分钟Youtube 都正常，然后就不能访问外网了。
ssh界面一直没关，连接出现问题后，试图重启ss服务。但得到提示是：Segmentation fault 
执行其它指令，如ps一样的错误，只能重启路由器。

Jan  5 17:30:20 kernel: ip_set: protocol 6
Jan  5 17:30:56 ss-redir[25713]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:30:57 ss-redir[25718]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 09:30:57 unbound: [25722:0] notice: init module 0: validator
Jan  5 09:30:57 unbound: [25722:0] notice: init module 1: iterator
Jan  5 17:30:57 kernel: warning: process `unbound' used the deprecated sysctl system call with 1.40.6.
Jan  5 09:30:57 unbound: [25722:0] info: start of service (unbound 1.9.3).
Jan  5 17:30:57 rc_service: service 25727:notify_rc restart_dnsmasq
Jan  5 17:30:57 dnsmasq[325]: exiting on receipt of SIGTERM
Jan  5 17:30:57 custom_config: Appending content of /jffs/configs/dnsmasq.conf.add.
Jan  5 17:30:58 ss-redir[25713]: listening at 0.0.0.0:1080
Jan  5 17:30:58 ss-redir[25718]: listening at 0.0.0.0:1080
Jan  5 17:30:58 ss-redir[25718]: running from root user
Jan  5 17:30:58 ss-redir[25713]: bind: Address already in use
Jan  5 17:30:58 ss-redir[25713]: bind() error
Jan  5 17:30:58 dnsmasq[25807]: started, version 2.80-95-g1aef66b cachesize 1500
Jan  5 17:30:58 dnsmasq[25807]: asynchronous logging enabled, queue limit is 5 messages
Jan  5 17:30:58 dnsmasq-dhcp[25807]: DHCP, IP range 192.168.50.2 -- 192.168.50.254, lease time 1d
Jan  5 17:30:58 dnsmasq[25807]: using nameserver 119.29.29.29#53 for domain www.apple.com 
...
Jan  5 17:30:58 dnsmasq[25807]: using nameserver 119.29.29.29#53 for domain phobos.apple.com 
Jan  5 17:30:58 dnsmasq[25807]: using 73466 more nameservers
Jan  5 17:30:58 dnsmasq[25807]: read /etc/hosts - 5 addresses
Jan  5 17:30:58 dnsmasq[25807]: using nameserver 192.168.1.1#53
Jan  5 17:30:58 dnsmasq[25807]: using nameserver 119.29.29.29#53 for domain www.apple.com 
...
Jan  5 17:30:58 dnsmasq[25807]: using nameserver 119.29.29.29#53 for domain prod-support.apple-support.akadns.net 
Jan  5 17:30:59 dnsmasq[25807]: using 73467 more nameservers
Jan  5 17:31:00 ss-redir[25836]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:31:00 ss-redir[25836]: listening at 0.0.0.0:1080
Jan  5 17:31:00 ss-redir[25836]: running from root user
Jan  5 17:32:00 ss-redir[25939]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:32:00 ss-redir[25939]: listening at 0.0.0.0:1080
Jan  5 17:32:00 ss-redir[25939]: running from root user
Jan  5 17:33:00 ss-redir[26041]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:33:00 ss-redir[26041]: listening at 0.0.0.0:1080
Jan  5 17:33:00 ss-redir[26041]: running from root user
Jan  5 17:34:00 ss-redir[26155]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:34:00 ss-redir[26155]: listening at 0.0.0.0:1080
Jan  5 17:34:00 ss-redir[26155]: running from root user
Jan  5 17:35:00 rc_service: service 26248:notify_rc restart_letsencrypt
Jan  5 17:35:00 ss-redir[26276]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:35:00 ss-redir[26276]: listening at 0.0.0.0:1080
Jan  5 17:35:00 ss-redir[26276]: running from root user
Jan  5 17:36:00 ss-redir[26405]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:36:00 ss-redir[26405]: listening at 0.0.0.0:1080
Jan  5 17:36:00 ss-redir[26405]: running from root user
Jan  5 17:36:17 ss-redir[26405]: server recv: Connection reset by peer
Jan  5 17:36:17 ss-redir[26405]: server recv: Connection reset by peer
Jan  5 17:36:17 ss-redir[26405]: server recv: Connection reset by peer
Jan  5 17:36:17 ss-redir[26405]: server recv: Connection reset by peer
Jan  5 17:37:00 ss-redir[26505]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:37:00 ss-redir[26505]: listening at 0.0.0.0:1080
Jan  5 17:37:00 ss-redir[26505]: running from root user
Jan  5 17:37:20 dnsmasq-dhcp[25807]: DHCPDISCOVER(br0) 44:09:b8:44:fe:f5 
Jan  5 17:37:20 dnsmasq-dhcp[25807]: DHCPOFFER(br0) 192.168.50.25 44:09:b8:44:fe:f5 
Jan  5 17:37:20 dnsmasq-dhcp[25807]: DHCPREQUEST(br0) 192.168.50.25 44:09:b8:44:fe:f5 
Jan  5 17:37:20 dnsmasq-dhcp[25807]: DHCPACK(br0) 192.168.50.25 44:09:b8:44:fe:f5 Chromecast-Ultra
Jan  5 17:38:11 ss-redir[26505]: remote recv: Connection timed out


Segmentation fault 

Jan  5 17:30:20 kernel: ip_set: protocol 6
Jan  5 17:30:56 ss-redir[25713]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:30:57 ss-redir[25718]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 09:30:57 unbound: [25722:0] notice: init module 0: validator
Jan  5 09:30:57 unbound: [25722:0] notice: init module 1: iterator
Jan  5 17:30:57 kernel: warning: process `unbound' used the deprecated sysctl system call with 1.40.6.
Jan  5 09:30:57 unbound: [25722:0] info: start of service (unbound 1.9.3).
Jan  5 17:30:57 rc_service: service 25727:notify_rc restart_dnsmasq
Jan  5 17:30:57 dnsmasq[325]: exiting on receipt of SIGTERM
Jan  5 17:30:57 custom_config: Appending content of /jffs/configs/dnsmasq.conf.add.
Jan  5 17:30:58 ss-redir[25713]: listening at 0.0.0.0:1080
Jan  5 17:30:58 ss-redir[25718]: listening at 0.0.0.0:1080
Jan  5 17:30:58 ss-redir[25718]: running from root user
Jan  5 17:30:58 ss-redir[25713]: bind: Address already in use
Jan  5 17:30:58 ss-redir[25713]: bind() error
Jan  5 17:30:58 dnsmasq[25807]: started, version 2.80-95-g1aef66b cachesize 1500
Jan  5 17:30:58 dnsmasq[25807]: asynchronous logging enabled, queue limit is 5 messages
Jan  5 17:30:58 dnsmasq-dhcp[25807]: DHCP, IP range 192.168.50.2 -- 192.168.50.254, lease time 1d
Jan  5 17:30:58 dnsmasq[25807]: using nameserver 119.29.29.29#53 for domain www.apple.com 
...
Jan  5 17:30:58 dnsmasq[25807]: using nameserver 119.29.29.29#53 for domain phobos.apple.com 
Jan  5 17:30:58 dnsmasq[25807]: using 73466 more nameservers
Jan  5 17:30:58 dnsmasq[25807]: read /etc/hosts - 5 addresses
Jan  5 17:30:58 dnsmasq[25807]: using nameserver 192.168.1.1#53
Jan  5 17:30:58 dnsmasq[25807]: using nameserver 119.29.29.29#53 for domain www.apple.com 
...
Jan  5 17:30:58 dnsmasq[25807]: using nameserver 119.29.29.29#53 for domain prod-support.apple-support.akadns.net 
Jan  5 17:30:59 dnsmasq[25807]: using 73467 more nameservers
Jan  5 17:31:00 ss-redir[25836]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:31:00 ss-redir[25836]: listening at 0.0.0.0:1080
Jan  5 17:31:00 ss-redir[25836]: running from root user
Jan  5 17:32:00 ss-redir[25939]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:32:00 ss-redir[25939]: listening at 0.0.0.0:1080
Jan  5 17:32:00 ss-redir[25939]: running from root user
Jan  5 17:33:00 ss-redir[26041]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:33:00 ss-redir[26041]: listening at 0.0.0.0:1080
Jan  5 17:33:00 ss-redir[26041]: running from root user
Jan  5 17:34:00 ss-redir[26155]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:34:00 ss-redir[26155]: listening at 0.0.0.0:1080
Jan  5 17:34:00 ss-redir[26155]: running from root user
Jan  5 17:35:00 rc_service: service 26248:notify_rc restart_letsencrypt
Jan  5 17:35:00 ss-redir[26276]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:35:00 ss-redir[26276]: listening at 0.0.0.0:1080
Jan  5 17:35:00 ss-redir[26276]: running from root user
Jan  5 17:36:00 ss-redir[26405]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:36:00 ss-redir[26405]: listening at 0.0.0.0:1080
Jan  5 17:36:00 ss-redir[26405]: running from root user
Jan  5 17:36:17 ss-redir[26405]: server recv: Connection reset by peer
Jan  5 17:36:17 ss-redir[26405]: server recv: Connection reset by peer
Jan  5 17:36:17 ss-redir[26405]: server recv: Connection reset by peer
Jan  5 17:36:17 ss-redir[26405]: server recv: Connection reset by peer
Jan  5 17:37:00 ss-redir[26505]: initializing ciphers... chacha20-ietf-poly1305
Jan  5 17:37:00 ss-redir[26505]: listening at 0.0.0.0:1080
Jan  5 17:37:00 ss-redir[26505]: running from root user
Jan  5 17:37:20 dnsmasq-dhcp[25807]: DHCPDISCOVER(br0) 44:09:b8:44:fe:f5 
Jan  5 17:37:20 dnsmasq-dhcp[25807]: DHCPOFFER(br0) 192.168.50.25 44:09:b8:44:fe:f5 
Jan  5 17:37:20 dnsmasq-dhcp[25807]: DHCPREQUEST(br0) 192.168.50.25 44:09:b8:44:fe:f5 
Jan  5 17:37:20 dnsmasq-dhcp[25807]: DHCPACK(br0) 192.168.50.25 44:09:b8:44:fe:f5 Chromecast-Ultra
Jan  5 17:38:11 ss-redir[26505]: remote recv: Connection timed out

**Comment by Acris** [comment]
有没有启用v2ray-plugin?

**Comment by BXXXXO** [comment]
没有。
{
  "server": "***",
  "server_port": 16534,
  "local_address": "0.0.0.0",
  "local_port": 1080,
  "password": "***",
  "timeout": 5,
  "method": "chacha20-ietf-poly1305",
  "mode": "tcp_only",
  "plugin": "",
  "plugin_opts": ""
}

# Route mode
## 0: GFW list.
## 1: Bypass mainland China.
## 2: Global mode.
mode=1

# UDP support
## 0: Disable UDP.
## 1: Enable UDP, require server side support.
udp=0

# LAN IPs
## Configure which LAN IP will pass transparent proxy.
## Default is 0.0.0.0/0, means all LAN devices will affected.
## You can assign a LAN IP like 192.169.1.125 means only this device can pass transparent proxy.
lan_ips=0.0.0.0/0

# China DNS IP
## Default is 119.29.29.29
china_dns_ip=119.29.29.29

**Comment by Acris** [comment]
好的，我排查一下，另外以后贴配置或者日志的时候，可以用<code>\`\`\`</code>包起来，方便查看。

**Comment by Acris** [comment]
执行`ss-merlin upgrade`升级至最新版本然后再观察一下是否还会出现该情况。

**Comment by BXXXXO** [comment]
年底事情多，一直没试。这几天又正常了，应该是服务器被墙的原因。非常感谢。

2020年1月13日 上午10:02，Acris Liu <notifications@github.com>写道：

执行ss-merlin upgrade升级至最新版本然后再观察一下是否还会出现该情况。
