### ISSUE TITLE
小白求问升级时出现错误如何解决？

### ISSUE THREAD

**Issue by KinseyWang** [Acris/shadowsocks-asuswrt-merlin#29]
最近几天不知道为什么突然就不能用了，ping过自己的服务器IP，是正常的没有被封，但路由不能翻墙了，想更新一下发现下面这个错误，无法更新，请问是何问题 如何解决？

Updating source code... 
Updating 4f554df..dc46bf1
error: Your local changes to the following files would be overwritten by merge:
	tools/statistics.sh
Please commit your changes or stash them before you merge.
Aborting
 There was an error updating. Try again later?

**Comment by Acris** [comment]
执行`ss-merlin uninstall`卸载然后重新安装即可。

**Comment by KinseyWang** [comment]
> 执行`ss-merlin uninstall`卸载然后重新安装即可。

那请问 卸载重装会导致配置信息都丢失吗？是否需要先备份服务器、密码什么的？

**Comment by Acris** [comment]
会丢失，建议备份。

**Comment by KinseyWang** [comment]
感谢 问题已经解决 网络畅通
