### ISSUE TITLE
你好，请问r6300v2能用吗

### ISSUE THREAD

**Issue by flytigerzhang** [Acris/shadowsocks-asuswrt-merlin#3]

**Comment by Acris** [comment]
R6300V2貌似没有合适的merlin.ng固件刷吧。如果你是用的koolshare的闭源改版固件，可以直接使用他们软件中心的科学上网软件。
目前只在R7000和AC86U上测试过，也欢迎你帮忙在R6300V2上协助进行测试。

**Comment by Comah** [comment]
我的就是6300v2 装上去了 没问题 版本号是4.18 使用中有什么问题还需要时间去测试

**Comment by Acris** [comment]
@Comah 4.18只是升级了shadowsocks-libev和v2ray-plugin的版本。
另外，你现在使用的，和该issue所属的项目无关系。

**Comment by flytigerzhang** [comment]
最近alpharacks买的vps，down掉了，ssh连不上，后台看status是 unavirable


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Comah <notifications@github.com>
发送时间: 2019年5月23日 20:56
收件人: Acris/shadowsocks-asuswrt-merlin <shadowsocks-asuswrt-merlin@noreply.github.com>
抄送: flytigerzhang <flytiger.zhang@qq.com>, Author <author@noreply.github.com>
主题: 回复：[Acris/shadowsocks-asuswrt-merlin] 你好，请问r6300v2能用吗 (#3)




我的就是6300v2 装上去了 没问题 版本号是4.18 使用中有什么问题还需要时间去测试

**Comment by Comah** [comment]
> @Comah 4.18只是升级了shadowsocks-libev和v2ray-plugin的版本。
> 另外，你现在使用的，和该issue所属的项目无任何关系。

明白 谢谢你 辛苦了
