### ISSUE TITLE
"Segmentation Fault" after enabling ss-merlin

### ISSUE THREAD

**Issue by ghprince** [Acris/shadowsocks-asuswrt-merlin#30]
First of all thanks a lot for creating this project! really appreciate the work!

I recently installed this on my AC87U following your instruction. The issue I am seeing now is that once I did `ss-merlin start`, after several minutes, my ssh session will give me `Segmentation Fault` for whatever command I sent. And if log out, I cannot login via ssh again. The symptom is it will accept my password and show the welcome message and then kick me out. Feels like ssh daemon is somehow in trouble.

When this happen, I log into Merlin webUI, I can see both CPU and memory are normal. At the end I have to reboot the router from webUI and everything is back to normal. But if I restart ss-merlin, this will happen again.

Any idea why ss-merlin will break ssh?

**Comment by Acris** [comment]
Try upgrade to the latest version with `ss-merlin upgrade` command.

**Comment by ghprince** [comment]
It doesn't help much with `ss-merlin upgrade`. I somehow have a feeling that this error happens when shadowsocks-libev failed to failed to connect to the server. But I am not sure which one is causing the other.

Anyway thx for the help, I don't think I will spend more time debugging this, and neither should you. I am closing this ticket.

**Comment by Acris** [comment]
Hi, try to uninstall by `ss-merlin uninstall` first, and install it again, this issue should be solved.
