### ISSUE TITLE
强烈反对写死啊 “Use real local lan ip instead of hard coded 192.168.0.0/24”

### ISSUE THREAD

**Issue by bobohb** [Acris/shadowsocks-asuswrt-merlin#31]
你把ip段设置死了，如果我路由器是192.168.1.1，流量就不能转发了...

**Comment by bobohb** [comment]
仔细看了文档，解决了

**Comment by Acris** [comment]
刚刚提交的最新版可以自动识别路由器的IP和子网掩码，使用`ss-merlin upgrade`更新即可。

**Comment by bobohb** [comment]
已更新，一切正常，非常感谢！

**Comment by Acris** [comment]
`ss-merlin.conf`配置文件中的lan_ips配置成`0.0.0.0/0`即可，这个值也是现在的默认配置，当然也可以自己指定IP段，如`192.168.1.0/24`等。正常情况下使用默认的`0.0.0.0/0`就可以了。
