### ISSUE TITLE
ERROR: bind: Address already in use

### ISSUE THREAD

**Issue by karpender** [Acris/shadowsocks-asuswrt-merlin#32]
你好，感谢开发这个功能，有以下问题请教：

`ss-merlin start`
启动服务，不能正常翻墙。

`ss-redir -c /opt/share/ss-merlin/etc/shadowsocks/config.json`
有报错：

```
 2020-03-01 11:41:00 ERROR: bind: Address already in use
 2020-03-01 11:41:00 ERROR: bind() error
```

config.json 文件如下：
```
{
  "server": "xxx.xxx.xxx",
  "server_port": 11368,
  "local_address": "0.0.0.0",
  "local_port": 1080,
  "password": "xxxxxxxx",
  "timeout": 600,
  "method": "chacha20-ietf-poly1305",
  "mode": "tcp_and_udp",
}
```
请问是什么原因？谢谢！

**Comment by Acris** [comment]
应该是1080端口被占用，可以尝试重启路由器，或者将配置文件中的`local_port`更换为别的端口。

**Comment by Acris** [comment]
从你描述来看，执行`ss-redir -c /opt/share/ss-merlin/etc/shadowsocks/config.json`之前有执行`ss-merlin stop`吗？如果没有的话应该是之前启动的进程占用了。

**Comment by karpender** [comment]
感谢回复，确实之前没执行`ss-merlin stop`，执行`ss-merlin stop`后，再执行`ss-redir -c /opt/share/ss-merlin/etc/shadowsocks/config.json`，输出信息如下：

```
 2020-03-01 13:51:24 INFO: initializing ciphers... chacha20-ietf-poly1305
 2020-03-01 13:51:24 INFO: listening at 0.0.0.0:1080
 2020-03-01 13:51:24 INFO: UDP relay enabled
 2020-03-01 13:51:24 INFO: running from root user
```

**Comment by karpender** [comment]
可能是加密方式不对，修改了`"method": "chacha20-ietf-poly1305",`为`"method": "chacha20-ietf",`，终于可以了。非常感谢！
