### ISSUE TITLE
arm-uclibc-strip

### ISSUE THREAD

**Issue by happy201807** [Acris/shadowsocks-asuswrt-merlin#35]
您好，
参照您的脚本已经完成了编译ss-local，
但是这个strip the binary file by arm-uclibc-strip是怎么编译安装的，能给点提示吗？

**Comment by Acris** [comment]
如果是`Broadcom SDK6/SDK7 ARM platform (RT-AC56 upto RT-AC5300)`，编译完后在容器执行：
```
. /root/env/bcm-sdk.sh
arm-uclibc-strip /home/build/arm/shadowsocks/bin/ss-local
```

如果是`Broadcom HND ARM platform (RT-AC86U)`，则执行：
```
. /root/env/bcm-hnd.sh
arm-linux-strip /home/build/arm/shadowsocks/bin/ss-local
```

**Comment by happy201807** [comment]
Thank you for your help and finally understand it.
