### ISSUE TITLE
configure: error: mbed TLS libraries not found.

### ISSUE THREAD

**Issue by happy201807** [Acris/shadowsocks-asuswrt-merlin#37]
checking for thread local storage (TLS) class... __thread
checking for mbedtls_cipher_setup in -lmbedcrypto... no
configure: error: mbed TLS libraries not found.

**Comment by happy201807** [comment]
您好，用现在的脚本大概率会出现这个错误，https://gist.github.com/happy201807/3b435e19c1f1ac1cca1f6369f98458b3，请问错在哪儿？

**Comment by Acris** [comment]
用这个测试下先：
https://gist.github.com/Acris/60abe3f1a17567a7986000745fbe2742

**Comment by happy201807** [comment]
> 
> 
> 用这个测试下先：
> https://gist.github.com/Acris/60abe3f1a17567a7986000745fbe2742

shadowsocks-libev-3.3.3/
shadowsocks-libev-3.3.3/AUTHORS
shadowsocks-libev-3.3.3/COPYING
shadowsocks-libev-3.3.3/Changes
shadowsocks-libev-3.3.3/INSTALL
shadowsocks-libev-3.3.3/Makefile.am
shadowsocks-libev-3.3.3/Makefile.in
shadowsocks-libev-3.3.3/README.md
shadowsocks-libev-3.3.3/acl/
shadowsocks-libev-3.3.3/acl/chn.acl
shadowsocks-libev-3.3.3/acl/gfwlist.acl
shadowsocks-libev-3.3.3/acl/local.acl
shadowsocks-libev-3.3.3/acl/server_block_chn.acl
shadowsocks-libev-3.3.3/acl/server_block_local.acl
shadowsocks-libev-3.3.3/aclocal.m4
shadowsocks-libev-3.3.3/auto/
shadowsocks-libev-3.3.3/auto/ar-lib
shadowsocks-libev-3.3.3/auto/compile
shadowsocks-libev-3.3.3/auto/config.guess
shadowsocks-libev-3.3.3/auto/config.sub
shadowsocks-libev-3.3.3/auto/depcomp
shadowsocks-libev-3.3.3/auto/install-sh
shadowsocks-libev-3.3.3/auto/ltmain.sh
shadowsocks-libev-3.3.3/auto/missing
shadowsocks-libev-3.3.3/completions/
shadowsocks-libev-3.3.3/completions/bash/
shadowsocks-libev-3.3.3/completions/bash/ss-local
shadowsocks-libev-3.3.3/completions/bash/ss-manager
shadowsocks-libev-3.3.3/completions/bash/ss-redir
shadowsocks-libev-3.3.3/completions/bash/ss-server
shadowsocks-libev-3.3.3/completions/bash/ss-tunnel
shadowsocks-libev-3.3.3/completions/zsh/
shadowsocks-libev-3.3.3/completions/zsh/_ss-local
shadowsocks-libev-3.3.3/completions/zsh/_ss-manager
shadowsocks-libev-3.3.3/completions/zsh/_ss-redir
shadowsocks-libev-3.3.3/completions/zsh/_ss-server
shadowsocks-libev-3.3.3/completions/zsh/_ss-tunnel
shadowsocks-libev-3.3.3/config.h.in
shadowsocks-libev-3.3.3/configure
shadowsocks-libev-3.3.3/configure.ac
shadowsocks-libev-3.3.3/debian/
shadowsocks-libev-3.3.3/debian/.gitignore
shadowsocks-libev-3.3.3/debian/README.Debian
shadowsocks-libev-3.3.3/debian/changelog
shadowsocks-libev-3.3.3/debian/compat
shadowsocks-libev-3.3.3/debian/config.json
shadowsocks-libev-3.3.3/debian/control
shadowsocks-libev-3.3.3/debian/copyright
shadowsocks-libev-3.3.3/debian/copyright.original
shadowsocks-libev-3.3.3/debian/doc-base
shadowsocks-libev-3.3.3/debian/libshadowsocks-libev-dev.install
shadowsocks-libev-3.3.3/debian/libshadowsocks-libev2.install
shadowsocks-libev-3.3.3/debian/rules
shadowsocks-libev-3.3.3/debian/shadowsocks-libev-local@.service
shadowsocks-libev-3.3.3/debian/shadowsocks-libev-redir@.service
shadowsocks-libev-3.3.3/debian/shadowsocks-libev-server@.service
shadowsocks-libev-3.3.3/debian/shadowsocks-libev-tunnel@.service
shadowsocks-libev-3.3.3/debian/shadowsocks-libev.default
shadowsocks-libev-3.3.3/debian/shadowsocks-libev.docs
shadowsocks-libev-3.3.3/debian/shadowsocks-libev.init
shadowsocks-libev-3.3.3/debian/shadowsocks-libev.install
shadowsocks-libev-3.3.3/debian/shadowsocks-libev.postinst
shadowsocks-libev-3.3.3/debian/shadowsocks-libev.postrm
shadowsocks-libev-3.3.3/debian/shadowsocks-libev.service
shadowsocks-libev-3.3.3/debian/source/
shadowsocks-libev-3.3.3/debian/source/format
shadowsocks-libev-3.3.3/debian/source.lintian-overrides
shadowsocks-libev-3.3.3/debian/tests/
shadowsocks-libev-3.3.3/debian/tests/control
shadowsocks-libev-3.3.3/debian/watch
shadowsocks-libev-3.3.3/doc/
shadowsocks-libev-3.3.3/doc/Makefile.am
shadowsocks-libev-3.3.3/doc/Makefile.in
shadowsocks-libev-3.3.3/doc/asciidoc.conf
shadowsocks-libev-3.3.3/doc/manpage-base.xsl
shadowsocks-libev-3.3.3/doc/manpage-bold-literal.xsl
shadowsocks-libev-3.3.3/doc/manpage-normal.xsl
shadowsocks-libev-3.3.3/doc/shadowsocks-libev.asciidoc
shadowsocks-libev-3.3.3/doc/ss-local.asciidoc
shadowsocks-libev-3.3.3/doc/ss-manager.asciidoc
shadowsocks-libev-3.3.3/doc/ss-nat.asciidoc
shadowsocks-libev-3.3.3/doc/ss-redir.asciidoc
shadowsocks-libev-3.3.3/doc/ss-server.asciidoc
shadowsocks-libev-3.3.3/doc/ss-tunnel.asciidoc
shadowsocks-libev-3.3.3/docker/
shadowsocks-libev-3.3.3/docker/alpine/
shadowsocks-libev-3.3.3/docker/alpine/Dockerfile
shadowsocks-libev-3.3.3/docker/alpine/README.md
shadowsocks-libev-3.3.3/docker/alpine/docker-compose.yml
shadowsocks-libev-3.3.3/docker/build/
shadowsocks-libev-3.3.3/docker/build/builder.Dockerfile
shadowsocks-libev-3.3.3/docker/build/dockerbuild.sh
shadowsocks-libev-3.3.3/docker/mingw/
shadowsocks-libev-3.3.3/docker/mingw/Dockerfile
shadowsocks-libev-3.3.3/docker/mingw/Makefile
shadowsocks-libev-3.3.3/docker/mingw/build.sh
shadowsocks-libev-3.3.3/docker/mingw/deps.sh
shadowsocks-libev-3.3.3/docker/mingw/make.bat
shadowsocks-libev-3.3.3/docker/mingw/prepare.sh
shadowsocks-libev-3.3.3/libbloom/
shadowsocks-libev-3.3.3/libbloom/.deps/
shadowsocks-libev-3.3.3/libbloom/.deps/libbloom_la-bloom.Plo
shadowsocks-libev-3.3.3/libbloom/.git
shadowsocks-libev-3.3.3/libbloom/.gitignore
shadowsocks-libev-3.3.3/libbloom/LICENSE
shadowsocks-libev-3.3.3/libbloom/Makefile
shadowsocks-libev-3.3.3/libbloom/Makefile.am
shadowsocks-libev-3.3.3/libbloom/Makefile.in
shadowsocks-libev-3.3.3/libbloom/README
shadowsocks-libev-3.3.3/libbloom/bloom.c
shadowsocks-libev-3.3.3/libbloom/bloom.h
shadowsocks-libev-3.3.3/libbloom/misc/
shadowsocks-libev-3.3.3/libbloom/misc/.gitignore
shadowsocks-libev-3.3.3/libbloom/misc/1.0/
shadowsocks-libev-3.3.3/libbloom/misc/1.0/linux.10000.1
shadowsocks-libev-3.3.3/libbloom/misc/1.0/linux.100000.1
shadowsocks-libev-3.3.3/libbloom/misc/1.0/linux.10000000.001
shadowsocks-libev-3.3.3/libbloom/misc/1.0/linux.10000000.01
shadowsocks-libev-3.3.3/libbloom/misc/1.0/linux.10000000.1
shadowsocks-libev-3.3.3/libbloom/misc/1.0/solaris.10000.1
shadowsocks-libev-3.3.3/libbloom/misc/1.0/solaris.100000.1
shadowsocks-libev-3.3.3/libbloom/misc/1.0/solaris.10000000.001
shadowsocks-libev-3.3.3/libbloom/misc/1.0/solaris.10000000.01
shadowsocks-libev-3.3.3/libbloom/misc/1.0/solaris.10000000.1
shadowsocks-libev-3.3.3/libbloom/misc/1.1/
shadowsocks-libev-3.3.3/libbloom/misc/1.1/linux.10000.1
shadowsocks-libev-3.3.3/libbloom/misc/1.1/linux.100000.1
shadowsocks-libev-3.3.3/libbloom/misc/1.1/linux.10000000.001
shadowsocks-libev-3.3.3/libbloom/misc/1.1/linux.10000000.01
shadowsocks-libev-3.3.3/libbloom/misc/1.1/linux.10000000.1
shadowsocks-libev-3.3.3/libbloom/misc/1.1/solaris.10000.1
shadowsocks-libev-3.3.3/libbloom/misc/1.1/solaris.100000.1
shadowsocks-libev-3.3.3/libbloom/misc/1.1/solaris.10000000.001
shadowsocks-libev-3.3.3/libbloom/misc/1.1/solaris.10000000.01
shadowsocks-libev-3.3.3/libbloom/misc/1.1/solaris.10000000.1
shadowsocks-libev-3.3.3/libbloom/misc/colcmp
shadowsocks-libev-3.3.3/libbloom/misc/colgraph
shadowsocks-libev-3.3.3/libbloom/misc/collisions/
shadowsocks-libev-3.3.3/libbloom/misc/collisions/collision_data_v1.2.gz
shadowsocks-libev-3.3.3/libbloom/misc/collisions/collision_data_v1.2.gz.png
shadowsocks-libev-3.3.3/libbloom/misc/collisions/collision_data_v1.3.gz
shadowsocks-libev-3.3.3/libbloom/misc/collisions/collision_data_v1.3.gz.png
shadowsocks-libev-3.3.3/libbloom/misc/collisions/dograph
shadowsocks-libev-3.3.3/libbloom/misc/test/
shadowsocks-libev-3.3.3/libbloom/misc/test/basic.c
shadowsocks-libev-3.3.3/libbloom/misc/test/test.c
shadowsocks-libev-3.3.3/libbloom/murmur2/
shadowsocks-libev-3.3.3/libbloom/murmur2/.deps/
shadowsocks-libev-3.3.3/libbloom/murmur2/.deps/.dirstamp
shadowsocks-libev-3.3.3/libbloom/murmur2/.deps/libbloom_la-MurmurHash2.Plo
shadowsocks-libev-3.3.3/libbloom/murmur2/.dirstamp
shadowsocks-libev-3.3.3/libbloom/murmur2/MurmurHash2.c
shadowsocks-libev-3.3.3/libbloom/murmur2/README
shadowsocks-libev-3.3.3/libbloom/murmur2/murmurhash2.h
shadowsocks-libev-3.3.3/libcork/
shadowsocks-libev-3.3.3/libcork/COPYING
shadowsocks-libev-3.3.3/libcork/INSTALL
shadowsocks-libev-3.3.3/libcork/Makefile.am
shadowsocks-libev-3.3.3/libcork/Makefile.in
shadowsocks-libev-3.3.3/libcork/include/
shadowsocks-libev-3.3.3/libcork/include/CMakeLists.txt
shadowsocks-libev-3.3.3/libcork/include/libcork/
shadowsocks-libev-3.3.3/libcork/include/libcork/cli/
shadowsocks-libev-3.3.3/libcork/include/libcork/cli/commands.h
shadowsocks-libev-3.3.3/libcork/include/libcork/cli.h
shadowsocks-libev-3.3.3/libcork/include/libcork/config/
shadowsocks-libev-3.3.3/libcork/include/libcork/config/arch.h
shadowsocks-libev-3.3.3/libcork/include/libcork/config/bsd.h
shadowsocks-libev-3.3.3/libcork/include/libcork/config/config.h
shadowsocks-libev-3.3.3/libcork/include/libcork/config/gcc.h
shadowsocks-libev-3.3.3/libcork/include/libcork/config/linux.h
shadowsocks-libev-3.3.3/libcork/include/libcork/config/macosx.h
shadowsocks-libev-3.3.3/libcork/include/libcork/config/mingw32.h
shadowsocks-libev-3.3.3/libcork/include/libcork/config/solaris.h
shadowsocks-libev-3.3.3/libcork/include/libcork/config/version.h
shadowsocks-libev-3.3.3/libcork/include/libcork/config/version.h.in
shadowsocks-libev-3.3.3/libcork/include/libcork/config.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/
shadowsocks-libev-3.3.3/libcork/include/libcork/core/allocator.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/api.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/attributes.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/byte-order.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/callbacks.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/error.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/gc.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/hash.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/id.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/mempool.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/net-addresses.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/timestamp.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/types.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core/u128.h
shadowsocks-libev-3.3.3/libcork/include/libcork/core.h
shadowsocks-libev-3.3.3/libcork/include/libcork/ds/
shadowsocks-libev-3.3.3/libcork/include/libcork/ds/array.h
shadowsocks-libev-3.3.3/libcork/include/libcork/ds/bitset.h
shadowsocks-libev-3.3.3/libcork/include/libcork/ds/buffer.h
shadowsocks-libev-3.3.3/libcork/include/libcork/ds/dllist.h
shadowsocks-libev-3.3.3/libcork/include/libcork/ds/hash-table.h
shadowsocks-libev-3.3.3/libcork/include/libcork/ds/managed-buffer.h
shadowsocks-libev-3.3.3/libcork/include/libcork/ds/ring-buffer.h
shadowsocks-libev-3.3.3/libcork/include/libcork/ds/slice.h
shadowsocks-libev-3.3.3/libcork/include/libcork/ds/stream.h
shadowsocks-libev-3.3.3/libcork/include/libcork/ds.h
shadowsocks-libev-3.3.3/libcork/include/libcork/helpers/
shadowsocks-libev-3.3.3/libcork/include/libcork/helpers/errors.h
shadowsocks-libev-3.3.3/libcork/include/libcork/helpers/gc.h
shadowsocks-libev-3.3.3/libcork/include/libcork/helpers/mingw.h
shadowsocks-libev-3.3.3/libcork/include/libcork/helpers/posix.h
shadowsocks-libev-3.3.3/libcork/include/libcork/os/
shadowsocks-libev-3.3.3/libcork/include/libcork/os/files.h
shadowsocks-libev-3.3.3/libcork/include/libcork/os/process.h
shadowsocks-libev-3.3.3/libcork/include/libcork/os/subprocess.h
shadowsocks-libev-3.3.3/libcork/include/libcork/os.h
shadowsocks-libev-3.3.3/libcork/include/libcork/threads/
shadowsocks-libev-3.3.3/libcork/include/libcork/threads/atomics.h
shadowsocks-libev-3.3.3/libcork/include/libcork/threads/basics.h
shadowsocks-libev-3.3.3/libcork/include/libcork/threads.h
shadowsocks-libev-3.3.3/libcork/src/
shadowsocks-libev-3.3.3/libcork/src/libcork/
shadowsocks-libev-3.3.3/libcork/src/libcork/cli/
shadowsocks-libev-3.3.3/libcork/src/libcork/cli/commands.c
shadowsocks-libev-3.3.3/libcork/src/libcork/core/
shadowsocks-libev-3.3.3/libcork/src/libcork/core/allocator.c
shadowsocks-libev-3.3.3/libcork/src/libcork/core/error.c
shadowsocks-libev-3.3.3/libcork/src/libcork/core/gc.c
shadowsocks-libev-3.3.3/libcork/src/libcork/core/hash.c
shadowsocks-libev-3.3.3/libcork/src/libcork/core/ip-address.c
shadowsocks-libev-3.3.3/libcork/src/libcork/core/mempool.c
shadowsocks-libev-3.3.3/libcork/src/libcork/core/timestamp.c
shadowsocks-libev-3.3.3/libcork/src/libcork/core/u128.c
shadowsocks-libev-3.3.3/libcork/src/libcork/ds/
shadowsocks-libev-3.3.3/libcork/src/libcork/ds/array.c
shadowsocks-libev-3.3.3/libcork/src/libcork/ds/bitset.c
shadowsocks-libev-3.3.3/libcork/src/libcork/ds/buffer.c
shadowsocks-libev-3.3.3/libcork/src/libcork/ds/dllist.c
shadowsocks-libev-3.3.3/libcork/src/libcork/ds/file-stream.c
shadowsocks-libev-3.3.3/libcork/src/libcork/ds/hash-table.c
shadowsocks-libev-3.3.3/libcork/src/libcork/ds/managed-buffer.c
shadowsocks-libev-3.3.3/libcork/src/libcork/ds/ring-buffer.c
shadowsocks-libev-3.3.3/libcork/src/libcork/ds/slice.c
shadowsocks-libev-3.3.3/libcork/src/libcork/posix/
shadowsocks-libev-3.3.3/libcork/src/libcork/posix/directory-walker.c
shadowsocks-libev-3.3.3/libcork/src/libcork/posix/env.c
shadowsocks-libev-3.3.3/libcork/src/libcork/posix/exec.c
shadowsocks-libev-3.3.3/libcork/src/libcork/posix/files.c
shadowsocks-libev-3.3.3/libcork/src/libcork/posix/mingw.c
shadowsocks-libev-3.3.3/libcork/src/libcork/posix/process.c
shadowsocks-libev-3.3.3/libcork/src/libcork/posix/subprocess.c
shadowsocks-libev-3.3.3/libcork/src/libcork/pthreads/
shadowsocks-libev-3.3.3/libcork/src/libcork/pthreads/thread.c
shadowsocks-libev-3.3.3/libipset/
shadowsocks-libev-3.3.3/libipset/INSTALL
shadowsocks-libev-3.3.3/libipset/Makefile.am
shadowsocks-libev-3.3.3/libipset/Makefile.in
shadowsocks-libev-3.3.3/libipset/include/
shadowsocks-libev-3.3.3/libipset/include/CMakeLists.txt
shadowsocks-libev-3.3.3/libipset/include/ipset/
shadowsocks-libev-3.3.3/libipset/include/ipset/bdd/
shadowsocks-libev-3.3.3/libipset/include/ipset/bdd/nodes.h
shadowsocks-libev-3.3.3/libipset/include/ipset/bits.h
shadowsocks-libev-3.3.3/libipset/include/ipset/errors.h
shadowsocks-libev-3.3.3/libipset/include/ipset/ipset.h
shadowsocks-libev-3.3.3/libipset/include/ipset/logging.h
shadowsocks-libev-3.3.3/libipset/src/
shadowsocks-libev-3.3.3/libipset/src/libipset/
shadowsocks-libev-3.3.3/libipset/src/libipset/bdd/
shadowsocks-libev-3.3.3/libipset/src/libipset/bdd/assignments.c
shadowsocks-libev-3.3.3/libipset/src/libipset/bdd/basics.c
shadowsocks-libev-3.3.3/libipset/src/libipset/bdd/bdd-iterator.c
shadowsocks-libev-3.3.3/libipset/src/libipset/bdd/expanded.c
shadowsocks-libev-3.3.3/libipset/src/libipset/bdd/reachable.c
shadowsocks-libev-3.3.3/libipset/src/libipset/bdd/read.c
shadowsocks-libev-3.3.3/libipset/src/libipset/bdd/write.c
shadowsocks-libev-3.3.3/libipset/src/libipset/general.c
shadowsocks-libev-3.3.3/libipset/src/libipset/map/
shadowsocks-libev-3.3.3/libipset/src/libipset/map/allocation.c
shadowsocks-libev-3.3.3/libipset/src/libipset/map/inspection-template.c.in
shadowsocks-libev-3.3.3/libipset/src/libipset/map/inspection.c
shadowsocks-libev-3.3.3/libipset/src/libipset/map/ipv4_map.c
shadowsocks-libev-3.3.3/libipset/src/libipset/map/ipv6_map.c
shadowsocks-libev-3.3.3/libipset/src/libipset/map/storage.c
shadowsocks-libev-3.3.3/libipset/src/libipset/set/
shadowsocks-libev-3.3.3/libipset/src/libipset/set/allocation.c
shadowsocks-libev-3.3.3/libipset/src/libipset/set/inspection-template.c.in
shadowsocks-libev-3.3.3/libipset/src/libipset/set/inspection.c
shadowsocks-libev-3.3.3/libipset/src/libipset/set/ipv4_set.c
shadowsocks-libev-3.3.3/libipset/src/libipset/set/ipv6_set.c
shadowsocks-libev-3.3.3/libipset/src/libipset/set/iterator.c
shadowsocks-libev-3.3.3/libipset/src/libipset/set/storage.c
shadowsocks-libev-3.3.3/m4/
shadowsocks-libev-3.3.3/m4/ax_pthread.m4
shadowsocks-libev-3.3.3/m4/ax_tls.m4
shadowsocks-libev-3.3.3/m4/cares.m4
shadowsocks-libev-3.3.3/m4/inet_ntop.m4
shadowsocks-libev-3.3.3/m4/libtool.m4
shadowsocks-libev-3.3.3/m4/ltoptions.m4
shadowsocks-libev-3.3.3/m4/ltsugar.m4
shadowsocks-libev-3.3.3/m4/ltversion.m4
shadowsocks-libev-3.3.3/m4/lt~obsolete.m4
shadowsocks-libev-3.3.3/m4/mbedtls.m4
shadowsocks-libev-3.3.3/m4/pcre.m4
shadowsocks-libev-3.3.3/m4/sodium.m4
shadowsocks-libev-3.3.3/m4/stack-protector.m4
shadowsocks-libev-3.3.3/rpm/
shadowsocks-libev-3.3.3/rpm/SOURCES/
shadowsocks-libev-3.3.3/rpm/SOURCES/etc/
shadowsocks-libev-3.3.3/rpm/SOURCES/etc/init.d/
shadowsocks-libev-3.3.3/rpm/SOURCES/etc/init.d/shadowsocks-libev
shadowsocks-libev-3.3.3/rpm/SOURCES/systemd/
shadowsocks-libev-3.3.3/rpm/SOURCES/systemd/shadowsocks-libev-local.service
shadowsocks-libev-3.3.3/rpm/SOURCES/systemd/shadowsocks-libev-local@.service
shadowsocks-libev-3.3.3/rpm/SOURCES/systemd/shadowsocks-libev-redir@.service
shadowsocks-libev-3.3.3/rpm/SOURCES/systemd/shadowsocks-libev-server@.service
shadowsocks-libev-3.3.3/rpm/SOURCES/systemd/shadowsocks-libev-tunnel@.service
shadowsocks-libev-3.3.3/rpm/SOURCES/systemd/shadowsocks-libev.default
shadowsocks-libev-3.3.3/rpm/SOURCES/systemd/shadowsocks-libev.service
shadowsocks-libev-3.3.3/rpm/SPECS/
shadowsocks-libev-3.3.3/rpm/SPECS/shadowsocks-libev.spec.in
shadowsocks-libev-3.3.3/rpm/genrpm.sh
shadowsocks-libev-3.3.3/scripts/
shadowsocks-libev-3.3.3/scripts/build_deb.sh
shadowsocks-libev-3.3.3/scripts/chroot_build.sh
shadowsocks-libev-3.3.3/scripts/code-format.bat
shadowsocks-libev-3.3.3/scripts/code-format.sh
shadowsocks-libev-3.3.3/scripts/git_archive.sh
shadowsocks-libev-3.3.3/scripts/git_version.sh
shadowsocks-libev-3.3.3/scripts/iperf.sh
shadowsocks-libev-3.3.3/shadowsocks-libev.pc.in
shadowsocks-libev-3.3.3/src/
shadowsocks-libev-3.3.3/src/Makefile.am
shadowsocks-libev-3.3.3/src/Makefile.in
shadowsocks-libev-3.3.3/src/acl.c
shadowsocks-libev-3.3.3/src/acl.h
shadowsocks-libev-3.3.3/src/aead.c
shadowsocks-libev-3.3.3/src/aead.h
shadowsocks-libev-3.3.3/src/base64.c
shadowsocks-libev-3.3.3/src/base64.h
shadowsocks-libev-3.3.3/src/cache.c
shadowsocks-libev-3.3.3/src/cache.h
shadowsocks-libev-3.3.3/src/common.h
shadowsocks-libev-3.3.3/src/crypto.c
shadowsocks-libev-3.3.3/src/crypto.h
shadowsocks-libev-3.3.3/src/http.c
shadowsocks-libev-3.3.3/src/http.h
shadowsocks-libev-3.3.3/src/jconf.c
shadowsocks-libev-3.3.3/src/jconf.h
shadowsocks-libev-3.3.3/src/json.c
shadowsocks-libev-3.3.3/src/json.h
shadowsocks-libev-3.3.3/src/local.c
shadowsocks-libev-3.3.3/src/local.h
shadowsocks-libev-3.3.3/src/manager.c
shadowsocks-libev-3.3.3/src/manager.h
shadowsocks-libev-3.3.3/src/netutils.c
shadowsocks-libev-3.3.3/src/netutils.h
shadowsocks-libev-3.3.3/src/plugin.c
shadowsocks-libev-3.3.3/src/plugin.h
shadowsocks-libev-3.3.3/src/ppbloom.c
shadowsocks-libev-3.3.3/src/ppbloom.h
shadowsocks-libev-3.3.3/src/protocol.h
shadowsocks-libev-3.3.3/src/redir.c
shadowsocks-libev-3.3.3/src/redir.h
shadowsocks-libev-3.3.3/src/resolv.c
shadowsocks-libev-3.3.3/src/resolv.h
shadowsocks-libev-3.3.3/src/rule.c
shadowsocks-libev-3.3.3/src/rule.h
shadowsocks-libev-3.3.3/src/server.c
shadowsocks-libev-3.3.3/src/server.h
shadowsocks-libev-3.3.3/src/shadowsocks.h
shadowsocks-libev-3.3.3/src/socks5.h
shadowsocks-libev-3.3.3/src/ss-nat
shadowsocks-libev-3.3.3/src/stream.c
shadowsocks-libev-3.3.3/src/stream.h
shadowsocks-libev-3.3.3/src/tls.c
shadowsocks-libev-3.3.3/src/tls.h
shadowsocks-libev-3.3.3/src/tunnel.c
shadowsocks-libev-3.3.3/src/tunnel.h
shadowsocks-libev-3.3.3/src/udprelay.c
shadowsocks-libev-3.3.3/src/udprelay.h
shadowsocks-libev-3.3.3/src/uthash.h
shadowsocks-libev-3.3.3/src/utils.c
shadowsocks-libev-3.3.3/src/utils.h
shadowsocks-libev-3.3.3/src/winsock.c
shadowsocks-libev-3.3.3/src/winsock.h
checking for arm-linux-gcc... arm-linux-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether arm-linux-gcc accepts -g... yes
checking for arm-linux-gcc option to accept ISO C89... none needed
checking whether arm-linux-gcc understands -c and -o together... yes
checking how to run the C preprocessor... arm-linux-gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-strip... no
checking for strip... strip
configure: WARNING: using cross tools not prefixed with host triplet
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of arm-linux-gcc... gcc3
checking for arm-linux-ar... arm-linux-ar
checking the archiver (arm-linux-ar) interface... ar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... arm-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by arm-linux-gcc... /root/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3/arm-brcm-linux-uclibcgnueabi/bin/ld
checking if the linker (/root/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3/arm-brcm-linux-uclibcgnueabi/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... no
checking for arm-linux-dumpbin... no
checking for arm-linux-link... no
checking for dumpbin... no
checking for link... link -dump
checking the name lister (nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to arm-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /root/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3/arm-brcm-linux-uclibcgnueabi/bin/ld option to reload object files... -r
checking for arm-linux-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for arm-linux-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for arm-linux-ar... (cached) arm-linux-ar
checking for archiver @FILE support... @
checking for arm-linux-strip... strip
checking for arm-linux-ranlib... arm-linux-ranlib
checking command to parse nm output from arm-linux-gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for arm-linux-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if arm-linux-gcc supports -fno-rtti -fno-exceptions... no
checking for arm-linux-gcc option to produce PIC... -fPIC -DPIC
checking if arm-linux-gcc PIC flag -fPIC -DPIC works... yes
checking if arm-linux-gcc static flag -static works... yes
checking if arm-linux-gcc supports -c -o file.o... yes
checking if arm-linux-gcc supports -c -o file.o... (cached) yes
checking whether the arm-linux-gcc linker (/root/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3/arm-brcm-linux-uclibcgnueabi/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... cross
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking checking for pcre includes in /home/build/arm/pcre... checking for pcre headers in /home/build/arm/pcre/include... ok
configure: adding /home/build/arm/pcre/lib to RPATH
checking for library containing pcre_exec... -lpcre
checking pcre.h usability... yes
checking pcre.h presence... no
configure: WARNING: pcre.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: pcre.h: proceeding with the compiler's result
checking for pcre.h... yes
checking pcre/pcre.h usability... no
checking pcre/pcre.h presence... no
checking for pcre/pcre.h... no
checking for arm-linux-gcc... (cached) arm-linux-gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether arm-linux-gcc accepts -g... (cached) yes
checking for arm-linux-gcc option to accept ISO C89... (cached) none needed
checking whether arm-linux-gcc understands -c and -o together... (cached) yes
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for thread local storage (TLS) class... __thread
checking for mbedtls_cipher_setup in -lmbedcrypto... no
configure: error: mbed TLS libraries not found.

**Comment by Acris** [comment]
已修复，使用这个脚本试试：
```
wget https://gist.githubusercontent.com/Acris/60abe3f1a17567a7986000745fbe2742/raw/a3f13416e51a97495428ce92b388ddbd54dd6efb/build-shadowsocks-libev-for-asuswrt-merlin.sh
```
