### ISSUE TITLE
[feature request]是否有考虑增加配置界面

### ISSUE THREAD

**Issue by hiwanz** [Acris/shadowsocks-asuswrt-merlin#43]
根据官方文档：[https://github.com/RMerl/asuswrt-merlin.ng/wiki/Addons-API](https://github.com/RMerl/asuswrt-merlin.ng/wiki/Addons-API)，梅林384.15版本后支持自定义插件，如果能做个UI配置界面会方便很多。

**Comment by Acris** [comment]
暂时不会。
因为我现在手上没支持梅林的路由器了，这个项目已经进入维护期，不会再增加新功能。
如果有好的想法及实现，欢迎提交Pull Request。
