### ISSUE TITLE
代理配置完成后无法使用，请大佬帮忙看看

### ISSUE THREAD

**Issue by RichardGTG** [Acris/shadowsocks-asuswrt-merlin#44]
路由器RT-AC86U，最新Asus-Merlin固件384.19，按照https://github.com/Acris/shadowsocks-asuswrt-merlin 的方法配置完成后无法使用。
最初表现：VPS ping不通，显示timeout，连接WiFi后，手机连上SS也翻不出去。
之后：关闭路由器防火墙之后，可以ping通，并且手机连上SS可以翻出去，但是不连还是不能翻。

奇怪的是，ss-merlin启动之后，原本没有被墙的境外网站也上不去了，比如github。

参考https://github.com/Acris/shadowsocks-asuswrt-merlin/issues/15 后的操作：

- 执行sh /opt/share/ss-merlin/scripts/update_gfwlist.sh，出现了/opt/share/ss-merlin/etc/dnsmasq.d/dnsmasq_gfwlist_ipset.conf

- 执行ipconfig /flushdns
但还是无法实现透明代理，劳烦大佬帮忙看看。

iptables -t nat -L
![Screenshot 2020-11-23 194538](https://user-images.githubusercontent.com/69584616/99958667-c2349d00-2dc4-11eb-8929-5ffb0136cf6c.jpg)

ipset list
![Screenshot 2020-11-23 194502](https://user-images.githubusercontent.com/69584616/99958772-ebedc400-2dc4-11eb-8dda-65dbc1530069.jpg)
![Screenshot 2020-11-23 194446](https://user-images.githubusercontent.com/69584616/99958786-ef814b00-2dc4-11eb-8cdf-ce9939219ecf.jpg)

ipset list gfwlist
![Screenshot 2020-11-23 192756](https://user-images.githubusercontent.com/69584616/99958932-2e170580-2dc5-11eb-914b-ccb5781aae86.jpg)

shadowsocks/config.json
![Screenshot 2020-11-23 193200](https://user-images.githubusercontent.com/69584616/99958988-3ec77b80-2dc5-11eb-99a1-216496def7ca.jpg)

ss-merlin.conf
![Screenshot 2020-11-23 192939](https://user-images.githubusercontent.com/69584616/99959020-4c7d0100-2dc5-11eb-8f01-58e79c975e4e.jpg)

**Comment by Acris** [comment]
尝试去掉`shadowsocks/config.json`中的`fast_open`这行，并且将`mode`那一行最后的逗号去除，然后执行`ss-merlin restart`看看能否使用。

如果还是不行，请排查：
1、服务端是否启用了某些插件，需要客户端配置才能连接？
2、使用ps命令看看有没有ss-redir进程？

**Comment by RichardGTG** [comment]
神奇啊！fast_open和逗号去掉之后就能用了。服务端其实是采用了simple obfs的混淆插件，协议是tls，不晓得是否支持这一插件？

**Comment by Acris** [comment]
`simple-obfs`已弃用，详见：[https://github.com/shadowsocks/simple-obfs#simple-obfs](https://github.com/shadowsocks/simple-obfs#simple-obfs)
建议使用`v2ray-plugin`：[https://github.com/shadowsocks/v2ray-plugin](https://github.com/shadowsocks/v2ray-plugin)
基于docker的服务端：https://github.com/Acris/docker-shadowsocks-libev

**Comment by RichardGTG** [comment]
好的，感谢大佬！
