### ISSUE TITLE
请问下lan_ips是否可以自定义多个设备？

### ISSUE THREAD

**Issue by harrywenjie** [Acris/shadowsocks-asuswrt-merlin#46]
先前的问题自己解决了，通过清空GFWlist，以及自定义的list，成功做了回国代理。
感谢你的工具。

**Comment by harrywenjie** [comment]
请问一下 ss-merlin.sample.conf 里面
lan_ips=0.0.0.0/0 
出了设置成一个设备，是否可以自定义多个设备呢？

**Comment by Acris** [comment]
目前只支持单个IP或者指定网段的形式，暂不支持配置多个IP或者IP段。

**Comment by harrywenjie** [comment]
谢谢，那我把需要回国的设备内网ip全部固定到一个网段下就行了。
用你的工具成功实现了自动分流。这样小米的各种IOT设备终于不傻了。
