### ISSUE TITLE
SOCKS5 realization

### ISSUE THREAD

**Issue by gjf** [Acris/shadowsocks-asuswrt-merlin#50]
According to the [start script](https://github.com/Acris/shadowsocks-asuswrt-merlin/blob/master/scripts/start_all_services.sh) this piece of code deploys a transparent proxy (ss-redir) on the router to send _all traffic_ thru remote ShadowSocks server.

But is it possible just to open SOCKS5 port on the router to redirect the traffic (ss-local)? I want to use such SOCKS5 not for all traffic but for a separate cases.

**Comment by Acris** [comment]
Hi, if you only need socks5 proxy, just install Entware, then install ss-local via `opkg update &&  opkg install shadowsocks-libev-ss-local`, then start ss-local via `ss-local -c ${CONFIG_FILE_PATH}/config.json -f /opt/var/run/ss-local.pid`, no need to use this project.

**Comment by gjf** [comment]
@Acris Thanks for suggestion!
However it doesn't work.
The client started OK however I cannot connect to my router IP on 1080 port stated in config.
Verbose logging shows no errors and the procerss is running but not possible to use.
`    {
      "server": "my.host.name",
      "server_port": 80,
      "local_port": 1080,
      "password": "MySuperPassword",
      "method": "chacha20-ietf-poly1305",
      "timeout": 5,
    }`

**Comment by gjf** [comment]
@Acris thanks a lot! It really works however I took v2ray-plugin from your project to work :-)
