### ISSUE TITLE
can you add kcptun for this

### ISSUE THREAD

**Issue by chuyume** [Acris/shadowsocks-asuswrt-merlin#6]
i tried this on XWRT-VORTEX and it works ,thank you very much.
i also want to use kcptun to speed up, and i tried to install kcptun and failed.
so cound you please add kcptun in this or separately create a new repository or tell me how to install kcptun on asus-merlin thanks very much. only ss on router makes me feel slow. 
i surf all the internet there is only this scrip working on asus-merlin easily. dont want to use koolshare merlin.

**Comment by Acris** [comment]
Try kcptun for linux arm5: https://github.com/xtaci/kcptun/releases/download/v20190611/kcptun-linux-arm5-20190611.tar.gz
tested on NETGEAR R7000 and work well.
