### ISSUE TITLE
user_ip_whitelist dont work

### ISSUE THREAD

**Issue by UnknownDef** [Acris/shadowsocks-asuswrt-merlin#61]
```
# IP whitelist
## You can add IP address to this file if you need the IP bypass proxy.
vi /opt/share/ss-merlin/rules/user_ip_whitelist.txt
```

when i add more then 1 ip address, ss writes 

```
Applying localips ipset rule...
: resolving to IPv4 address failedparse 162.159.138.232
: resolving to IPv4 address failedparse 168.159.133.233
```

it works only with 1 ip address?

**Comment by UnknownDef** [comment]
> It can add multiple IP addresses, one per line.

When i add 2 ip in 2 lines
```
162.159.138.232
168.159.133.233
```

is says this and dont work...
```
Applying localips ipset rule...
: resolving to IPv4 address failedparse 162.159.138.232
: resolving to IPv4 address failedparse 168.159.133.233
```

**Comment by ElectroBandit** [comment]
> when i add more then 1 ip address, ss writes

Don't use Windows Notepad because it incorrectly interprets the newline character. I had the same problem with a list of domains - only the first domain worked. Then I edited the list using vi, and it worked.
